name: linting
on:
  push:
    branches: main
    paths: "*.py"

jobs:
  Code-Test:
    runs-on: ubuntu-latest
    steps:
      - name: clone the code   # Clone the code from the repo into this runner
        uses: actions/checkout@v7

      - name: install linter
        run: pip install ruff
       
      - name: check the files for lining
        run: ruff check .
       
